# Generated by Django 2.1.8 on 2019-05-11 18:39
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_restricted',
            field=models.BooleanField(default=False, help_text='Do not allow others to add events to this group'),
        ),
    ]
