# Generated by Django 2.1.8 on 2019-05-11 18:31
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('slug', models.SlugField(blank=True, help_text='slug', null=True, verbose_name='slug')),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('link1', models.URLField(blank=True, null=True)),
                ('link2', models.URLField(blank=True, null=True)),
                ('link3', models.URLField(blank=True, null=True)),
                ('link4', models.URLField(blank=True, null=True)),
                ('link5', models.URLField(blank=True, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('show_nb', models.BooleanField(default=False)),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='street')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='city')),
                ('zip_code', models.CharField(blank=True, max_length=16, null=True, verbose_name='zip code')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('edit_secret', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='edit secret')),
                ('view_secret', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='view secret')),
            ],
            options={
                'verbose_name': 'Event',
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Allowed formats: JPEG, PNG, GIF. Please upload high resolution (>1000 pixels wide).', upload_to='', verbose_name='image')),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='0=first, 1=second etc.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='calendar.Event')),
            ],
            options={
                'ordering': ('priority',),
            },
        ),
        migrations.CreateModel(
            name='EventTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='start')),
                ('end', models.DateTimeField(verbose_name='end')),
                ('comment', models.CharField(blank=True, help_text='Leave blank and nothing will be shown to readers', max_length=255, null=True, verbose_name='comment')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='calendar.Event')),
            ],
            options={
                'verbose_name': 'Event time',
                'ordering': ('start', 'end'),
            },
        ),
        migrations.CreateModel(
            name='EventUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event time',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('every_week', models.BooleanField(default=False)),
                ('first_week_of_month', models.BooleanField(default=False)),
                ('second_week_of_month', models.BooleanField(default=False)),
                ('third_week_of_month', models.BooleanField(default=False)),
                ('last_week_of_month', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
        ),
        migrations.AddField(
            model_name='interval',
            name='weekday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar.Weekday'),
        ),
    ]
