# Generated by Django 2.1.8 on 2019-05-11 18:31
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('calendar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='users.Group'),
        ),
        migrations.AddField(
            model_name='event',
            name='interval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calendar.Interval'),
        ),
        migrations.AddField(
            model_name='event',
            name='owner_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_events', to='users.Group', verbose_name='owner (group)'),
        ),
        migrations.AddField(
            model_name='event',
            name='owner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_events', to=settings.AUTH_USER_MODEL, verbose_name='owner (user)'),
        ),
    ]
