# Generated by Django 2.1.8 on 2019-05-11 18:45
from django.db import migrations
from django.utils.translation import gettext as _

weekdays = {
    0: _("Monday"),
    1: _("Tuesday"),
    2: _("Wednesday"),
    3: _("Thursday"),
    4: _("Friday"),
    5: _("Saturday"),
    6: _("Sunday"),
}


def create_weekdays(apps, schema_editor):
    Weekday = apps.get_model('calendar', 'Weekday')

    for k, v in weekdays.items():
        Weekday.objects.get_or_create(number=k, name=v)


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0003_weekday_number'),
    ]

    operations = [
        migrations.RunPython(create_weekdays),
    ]
