# Generated by Django 2.1.8 on 2019-05-26 16:40
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0004_weekdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue_name',
            field=models.CharField(blank=True, help_text='If left blank, will be copied from host group', max_length=255, null=True, verbose_name='venue name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, help_text='If left blank, will be copied from host group', max_length=255, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.ForeignKey(blank=True, help_text='A group may host an event and be displayed as the author of the event text.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='users.Group'),
        ),
        migrations.AlterField(
            model_name='event',
            name='interval',
            field=models.ForeignKey(help_text='Repeats the event automatically at some interval', on_delete=django.db.models.deletion.PROTECT, to='calendar.Interval'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, help_text='The part of a URL that is displayed in dukop.dk/event/<slug>/', null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='event',
            name='street',
            field=models.CharField(blank=True, help_text='If left blank, will be copied from host group', max_length=255, null=True, verbose_name='street'),
        ),
        migrations.AlterField(
            model_name='event',
            name='zip_code',
            field=models.CharField(blank=True, help_text='If left blank, will be copied from host group', max_length=16, null=True, verbose_name='zip code'),
        ),
    ]
